[project]
name = "datacamp-ml-track"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ömer Yaslıtaş", email = "omer.yaslitas@metu.edu.tr" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "kagglehub>=1.0.2",
    "matplotlib>=3.11.2",
    "mlxtend>=0.25.0",
    "nltk>=3.10.3",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
datacamp-ml-track = "datacamp_ml_track:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
